In [1]:
import tushare as ts  # 引入tushare包
hs300 = ts.get_hs300s() # 获取沪深300的股票数据
hs300

          date    code  name  weight
0   2020-05-29  600000  浦发银行    0.95
1   2020-05-29  600004  白云机场    0.13
2   2020-05-29  600009  上海机场    0.53
3   2020-05-29  600010  包钢股份    0.19
4   2020-05-29  600011  华能国际    0.15
..         ...     ...   ...     ...
295 2020-05-29  300347  泰格医药    0.34
296 2020-05-29  300408  三环集团    0.16
297 2020-05-29  300413  芒果超媒    0.22
298 2020-05-29  300433  蓝思科技    0.16
299 2020-05-29  300498  温氏股份    0.75

[300 rows x 4 columns]

In [2]:
hs300 = hs300['code'].tolist()  #  转换成列表
hs300[:10]

['600000',
 '600004',
 '600009',
 '600010',
 '600011',
 '600015',
 '600016',
 '600018',
 '600019',
 '600023']

In [3]:
# 获取基本面数据
stock_basics = ts.get_stock_basics()
type(stock_basics)
stock_basics

本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2

,name,industry,area,pe,outstanding,totals,totalAssets,liquidAssets,fixedAssets,reserved,...,bvps,pb,timeToMarket,undp,perundp,rev,profit,gpr,npr,holders
code,,,,,,,,,,,,,,,,,,,,,
688088,虹软科技,软件服务,浙江,185.33,0.40,4.06,28.51,27.61,0.16,18.76,...,6.30,14.29,20190722,2.80,0.69,31.00,62.04,89.69,29.85,13145.0
002740,爱迪尔,服饰,福建,53.48,2.42,4.54,46.29,35.69,0.44,17.83,...,5.47,0.98,20150122,1.85,0.41,-36.94,-24.21,28.70,5.30,23921.0
002305,南国置业,区域地产,湖北,0.00,17.33,17.34,278.52,267.00,6.42,13.07,...,2.26,1.21,20091106,6.40,0.37,-96.03,-1615.90,-198.60,-188.02,59989.0
600586,金晶科技,玻璃,山东,36.93,14.29,14.29,93.31,35.52,41.35,18.13,...,2.88,1.06,20020815,7.32,0.51,-17.13,-52.27,18.66,2.97,95801.0
300687,赛意信息,软件服务,广东,430.68,0.94,2.18,12.90,9.17,0.20,2.99,...,3.76,6.22,20170803,2.81,1.29,16.39,1018.83,23.04,1.23,11295.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
688180,君实生物,生物制药,上海,0.00,0.00,0.00,44.12,19.11,3.28,41.80,...,0.00,0.00,0,-19.99,0.00,26375.50,-3.39,88.30,-96.43,0.0
688277,天智航,医疗保健,北京,0.00,0.00,0.00,6.75,4.13,0.19,2.75,...,0.00,0.00,0,-0.83,0.00,0.00,0.00,63.50,-62.27,0.0
688309,恒誉环保,环境保护,山东,0.00,0.00,0.00,3.16,1.87,0.82,0.22,...,0.00,0.00,0,1.34,0.00,0.00,0.00,51.59,24.17,0.0
688377,迪威尔,专用机械,江苏,0.00,0.00,0.00,12.24,6.88,3.15,2.58,...,0.00,0.00,0,2.98,0.00,0.00,0.00,28.28,15.24,0.0
688528,秦川物联,电器仪表,四川,0.00,0.00,0.00,4.69,2.58,1.44,0.79,...,0.00,0.00,0,0.84,0.00,0.00,0.00,44.23,13.57,0.0

In [4]:
# 从基本面数据种获取相关信息,获取hs300的
stock_basics.reset_index(inplace=True) # 重置DateFrame的索引
data1 = stock_basics.loc[stock_basics['code'].isin(hs300),  # 行标签
                        ['code','name','industry','pe','pb','esp','rev','profit']]  #列标签

data1.columns = ['代码','名称','行业','PE','PB','EPS','收入%','利润%']
data1.head()

         代码    名称    行业      PE     PB    EPS    收入%     利润%
31   601138  工业富联  通信设备   41.28   3.38  0.090  -0.08  -35.01
85   603160  汇顶科技   元器件  126.03  15.40  0.440  10.27  -50.58
94   002008  大族激光  电器仪表   86.15   4.41  0.100 -28.96  -33.25
99   600999  招商证券    证券   18.79   1.87  0.240   5.17  -15.49
108  601012  隆基股份  电气设备   19.23   4.86  0.494  50.60  204.92

In [5]:
#获取盈利能力数据
stock_profit = ts.get_profit_data(2017,1)

本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
[Getting data:]############################################################

In [6]:
data2 = stock_profit.loc[stock_profit['code'].isin(hs300),  #行标签
                         ['code','roe','gross_profit_rate','net_profit_ratio']] # 列标签
data2.columns = ['代码','ROE','毛利率','净利率']
data2 = round(data2,2)  # 保留2位小数
data2.head()

        代码    ROE    毛利率    净利率
19  002027  12.20  67.60  45.72
22  600309  11.26  39.23  19.94
26  002714  10.72  40.47  34.55
34  300136   9.58  29.69  28.43
36  002304   9.52  61.23  36.14

In [7]:
# 获取成长能力数据
stock_growth = ts.get_growth_data(2019,1)
stock_growth

本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
[Getting data:]##############################################################

,code,name,mbrg,nprg,nav,targ,epsg,seg
0,603032,德新交运,-28.5719,30366.9407,58.1348,74.4780,1108.3333,58.3622
1,002738,中矿资源,134.3683,11164.6389,215.0591,201.0570,3140.0000,219.8668
2,000779,甘咨询,622.3124,9921.7010,474.7857,430.5810,4910.3448,471.8393
3,600455,博通股份,13.5206,8553.9572,10.0557,4.8619,-2378.0000,8.2498
4,600985,淮北矿业,6844.0510,8145.0340,1002.2831,2280.2556,975.0000,889.5426
...,...,...,...,...,...,...,...,...
3682,300074,华平股份,-17.2644,NaN,0.2630,-0.6208,24.8588,0.5344
3683,000506,中润资源,-26.3596,NaN,12.4125,1.9826,-152.4096,13.7771
3684,600313,农发种业,48.5663,NaN,-0.8101,-8.3273,-25.5102,2.4927
3685,002339,积成电子,21.6513,NaN,3.6564,-1.6335,-7.6923,3.5905
3686,300795,米奥会展,16.2850,NaN,-100.0000,-100.0000,15.3846,-100.0000

In [8]:
data3 = stock_growth.loc[stock_growth['code'].isin(hs300),  # isin： 是否存在
                        ['code','nprg']]
data3.columns = ['代码','N增长率']
data3 = round(data3,2)  # 实现4舍5入
data3.head()

        代码     N增长率
11  300413  3569.37
21  603160  2039.95
56  002607  1043.82
62  601555   872.86
92  600570   609.32

In [9]:
from functools import reduce
import pandas as pd

merge = lambda x,y: pd.merge(x,y,how='left',on='代码')
data = reduce(merge,[data1,data2,data3])
data.drop_duplicates(inplace=True)  # 去掉重复数据
data.head()

,代码,名称,行业,PE,PB,EPS,收入%,利润%,ROE,毛利率,净利率,N增长率
0,601138,工业富联,通信设备,41.28,3.38,0.090,-0.08,-35.01,NaN,NaN,NaN,8.30
1,603160,汇顶科技,元器件,126.03,15.40,0.440,10.27,-50.58,6.02,47.36,23.97,2039.95
2,002008,大族激光,电器仪表,86.15,4.41,0.100,-28.96,-33.25,2.72,40.76,9.95,-56.31
3,600999,招商证券,证券,18.79,1.87,0.240,5.17,-15.49,1.95,57.36,48.66,97.06
4,601012,隆基股份,电气设备,19.23,4.86,0.494,50.60,204.92,4.17,31.33,16.35,25.31

In [10]:
data['估值系数'] = data['PE'] * data['PB']
data = round(data,2)
data.head()

,代码,名称,行业,PE,PB,EPS,收入%,利润%,ROE,毛利率,净利率,N增长率,估值系数
0,601138,工业富联,通信设备,41.28,3.38,0.09,-0.08,-35.01,NaN,NaN,NaN,8.30,139.53
1,603160,汇顶科技,元器件,126.03,15.40,0.44,10.27,-50.58,6.02,47.36,23.97,2039.95,1940.86
2,002008,大族激光,电器仪表,86.15,4.41,0.10,-28.96,-33.25,2.72,40.76,9.95,-56.31,379.92
3,600999,招商证券,证券,18.79,1.87,0.24,5.17,-15.49,1.95,57.36,48.66,97.06,35.14
4,601012,隆基股份,电气设备,19.23,4.86,0.49,50.60,204.92,4.17,31.33,16.35,25.31,93.46

In [11]:
data_filter = data.loc[(data['估值系数']<60) & (data['ROE']>5),
                      ['代码','名称','PE','PB','估值系数','ROE','收入%']]
data_filter.head()

         代码     名称    PE     PB  估值系数   ROE    收入%
17   600816  *ST安信  0.00   1.74  0.00  7.55   0.00
53   601225   陕西煤业  7.70   1.19  9.16  7.13  27.28
61   600340   华夏幸福  5.98   1.45  8.67  5.64  89.64
88   601577   长沙银行  4.42   0.75  3.32  5.12  13.08
106  601888   中国国旅  0.00  12.52  0.00  5.40 -44.23

In [12]:
print('筛选结果共 %d 只个股' % len(data_filter))

筛选结果共 16 只个股

In [13]:
# 按照选定字段对数据进行排序
data_filter.sort_values(['估值系数'],ascending=True,inplace=True)  # sort_values 是数值进行排序
data_filter.head(10)

         代码     名称     PE     PB   估值系数   ROE    收入%
17   600816  *ST安信   0.00   1.74   0.00  7.55   0.00
106  601888   中国国旅   0.00  12.52   0.00  5.40 -44.23
143  600115   东方航空   0.00   1.11   0.00  5.62 -48.58
278  002466   天齐锂业   0.00   6.27   0.00  7.73 -27.57
285  000423   东阿阿胶   0.00   2.49   0.00  6.74 -66.11
88   601577   长沙银行   4.42   0.75   3.32  5.12  13.08
194  600177    雅戈尔   6.73   1.05   7.07  5.47  51.07
61   600340   华夏幸福   5.98   1.45   8.67  5.64  89.64
53   601225   陕西煤业   7.70   1.19   9.16  7.13  27.28
129  601318   中国平安  12.67   1.91  24.20  5.60 -13.22

In [14]:
# 数据分类
def map_func(x):
    if x['ROE'] > 5:
        return '高成长'
    elif x['ROE'] >= 0 and x['ROE'] <= 5:
        return '低成长'
    elif x['ROE'] < 0:
        return '亏损'

In [15]:
data['成长性'] = data.apply(map_func,axis=1)
data.tail(10)

,代码,名称,行业,PE,PB,EPS,收入%,利润%,ROE,毛利率,净利率,N增长率,估值系数,成长性
298,002938,鹏鼎控股,元器件,94.87,5.79,0.13,-6.31,66.33,NaN,NaN,NaN,3.30,549.30,None
299,601162,天风证券,证券,129.39,2.38,0.01,-18.62,-37.36,NaN,NaN,NaN,210.88,307.95,None
300,600061,国投资本,证券,21.23,1.36,0.15,-73.60,-47.80,2.14,3.70,260.50,136.43,28.87,低成长
301,002460,赣锋锂业,小金属,2254.43,8.49,0.01,-18.88,-96.94,5.21,34.04,21.82,-29.47,19140.11,高成长
302,300122,智飞生物,生物制药,77.39,25.52,0.32,14.87,2.85,2.33,93.82,37.17,93.38,1974.99,低成长
303,300142,沃森生物,生物制药,0.00,17.07,-0.01,-36.34,-146.78,-0.92,55.84,-34.00,78.17,0.00,亏损
304,002607,中公教育,文教休闲,369.48,82.59,0.02,-6.22,9.52,1.31,7.41,1.78,1043.82,30515.35,低成长
305,600118,中国卫星,航空,192.75,6.44,0.04,-16.59,-26.83,1.17,13.30,5.18,5.73,1241.31,低成长
306,601236,红塔证券,证券,38.11,5.33,0.13,152.45,135.77,NaN,NaN,NaN,NaN,203.13,None
307,300015,爱尔眼科,医疗保健,558.81,26.56,0.02,-26.86,-73.41,5.26,44.06,12.99,32.54,14841.99,高成长

In [16]:
# 对高成长分类，按照“估值系数”做升序排列
data_growth = data[data['成长性'] == '高成长'].sort_values(['估值系数'],ascending=True)
data_growth.head(10)

,代码,名称,行业,PE,PB,EPS,收入%,利润%,ROE,毛利率,净利率,N增长率,估值系数,成长性
278,002466,天齐锂业,小金属,0.00,6.27,-0.34,-27.57,-549.52,7.73,68.79,38.15,-63.74,0.00,高成长
17,600816,*ST安信,多元金融,0.00,1.74,-0.12,0.00,-313.21,7.55,83.30,62.47,-70.46,0.00,高成长
143,600115,东方航空,空运,0.00,1.11,-0.24,-48.58,-296.06,5.62,12.44,11.48,0.56,0.00,高成长
106,601888,中国国旅,旅游服务,0.00,12.52,-0.06,-44.23,-105.21,5.40,30.14,12.42,104.16,0.00,高成长
285,000423,东阿阿胶,中成药,0.00,2.49,-0.13,-66.11,-121.33,6.74,70.80,36.06,-35.69,0.00,高成长
88,601577,长沙银行,银行,4.42,0.75,0.45,13.08,12.01,5.12,47.89,37.67,10.59,3.32,高成长
194,600177,雅戈尔,服饰,6.73,1.05,0.22,51.07,37.05,5.47,46.77,37.17,48.31,7.07,高成长
61,600340,华夏幸福,区域地产,5.98,1.45,0.95,89.64,-2.59,5.64,62.39,22.47,32.96,8.67,高成长
53,601225,陕西煤业,煤炭开采,7.70,1.19,0.24,27.28,-15.08,7.13,55.72,21.78,-11.81,9.16,高成长
129,601318,中国平安,保险,12.67,1.91,1.47,-13.22,-42.74,5.60,12.29,8.67,70.37,24.20,高成长

In [17]:
def group_func(df):
    return df.sort_values(['估值系数'],ascending=True)[:2]

data_grouped = data.groupby('成长性').apply(group_func)
data_grouped

             代码     名称    行业   PE     PB   EPS    收入%      利润%   ROE    毛利率  \
成长性
亏损  25   600588   用友网络  软件服务  0.0  20.39 -0.07 -13.06  -389.30 -3.01  61.38
    132  600100   同方股份  IT设备  0.0   1.40 -0.17 -15.76  -194.56 -1.26  15.25
低成长 268  600733   北汽蓝谷  汽车整车  0.0   1.35 -0.12 -53.12 -2142.76  0.19  22.78
    79   601633   长城汽车  汽车整车  0.0   1.39 -0.07 -43.94  -184.08  3.96  21.74
高成长 278  002466   天齐锂业   小金属  0.0   6.27 -0.34 -27.57  -549.52  7.73  68.79
    17   600816  *ST安信  多元金融  0.0   1.74 -0.12   0.00  -313.21  7.55  83.30

           净利率   N增长率  估值系数  成长性
成长性
亏损  25  -22.37    NaN   0.0   亏损
    132  -6.65    NaN   0.0   亏损
低成长 268   3.59    NaN   0.0  低成长
    79    8.42 -62.00   0.0  低成长
高成长 278  38.15 -63.74   0.0  高成长
    17   62.47 -70.46   0.0  高成长

In [18]:
data.groupby('成长性').size()

成长性
亏损      10
低成长    217
高成长     54
dtype: int64